### ISSUE TITLE
Dashboard Suggestions

### ISSUE THREAD

**Issue by Mike-E-angelo** [nextreleaseio/next-release#18]
Not sure if this is the best place for this, but thought I'd start somewhere. 😁

Suggestions for the dashboard:

- **Labels**:  It would be super useful to have the ability to add more labels.  For instance, we have `housekeeping` and `performance` that might show up.  There's also `security` as well.  Being able to add (and order) those would be great. 👍
- **Header**:  Having a header that's applied to every new release would be cool.  It should of course be pre-populated with `Powered by [NextRelease](https://nextrelease.io).` so you get additional eyeballs to your warez.  It should be a template defined like labels, but once applied to a release you are able to edit it like other items there.
- **Footer**: Same as header, but at the foot. :)  Can be something like `For more details or to report any issues/questions with this release, check out [our repo](http://github.com/<repo>/issues/).`

**Comment by donaldwasserman** [comment]
These are all great suggestions! Thanks!
