### ISSUE TITLE
First Release: Minor Issues

### ISSUE THREAD

**Issue by Mike-E-angelo** [nextreleaseio/next-release#19]
Looking good!  I noticed some issues. Check it out:

![](https://i.imgur.com/LQWhZ55.png)

1. Looks like the `#4` in the first issue doesn't link correctly.  It's based on this PR: https://github.com/ExtendedXmlSerializer/NextRelease/pull/4
1. My name is not higlighted correctly.  The link goes to "mike" as well.

Everything else is pretty legit thus far. 👍

**Comment by donaldwasserman** [comment]
When you solve a problem with a regex....

**Comment by Mike-E-angelo** [comment]
FWIW this appears to be still happening, @donaldwasserman: 

![](https://i.imgur.com/YyV6aoK.png)

**Comment by donaldwasserman** [comment]
We haven't actually yet deployed this fix. But I did in fact spend time googling "why isn't my regex working" 😆
