### ISSUE TITLE
State Problem: Unexpected Status

### ISSUE THREAD

**Issue by Mike-E-angelo** [nextreleaseio/next-release#20]
Trying to be low maintenance here. 😁 👼

Consider this PR:

https://github.com/ExtendedXmlSerializer/NextRelease/pull/8

Notice that it makes use of [PR-Labeler](https://github.com/TimonVS/pr-labeler-action)

At first, there is no label and NextRelease states there's a problem.

So far so good.

Then PR-Labeler identifies and applies `enhancement`, and NextRelease goes green.

I then apply a `breaking change` label as it is a feature that introduces one.

NextRelease does not update in the `Pending Release`:

![](https://i.imgur.com/Lr3X2f5.png)

While the next version is accurate (`1.0.0`), the item in the list is denoted as a feature.  While that is technically accurate, it is also a breaking change as well.  The expectation here is that the item would be promoted to a breaking change to reflect the new version.

**Comment by Mike-E-angelo** [comment]
This appears to be a state problem in the NextRelease editor.  

It published as expected:
https://github.com/ExtendedXmlSerializer/NextRelease/releases/tag/1.0.0

**Comment by donaldwasserman** [comment]
@Mike-EEE Thanks for reporting this. We'll get this turned around!
