### ISSUE TITLE
Tag Format and Message Appears to be Ignored

### ISSUE THREAD

**Issue by Mike-E-angelo** [nextreleaseio/next-release#21]
So much for being low maintenance. 😆

I have my settings applied as such:

![](https://i.imgur.com/kbWEtKb.png)

Here is an example of what I am seeing on:

https://github.com/ExtendedXmlSerializer/NextRelease/releases/tag/1.0.2

In particular:
![](https://i.imgur.com/0eESlZr.png)

Not sure if there is another setting or something else to consider, so thought I would bring it up.

The other issue is the `Tag Message` setting.  I do not see that applied anywhere in the release.

**Comment by Mike-E-angelo** [comment]
Cool!  Has this been fixed, then @donaldwasserman?  Or are you closing items so I can get out of your hair? 😆

**Comment by donaldwasserman** [comment]
This _should_ be fixed.

**Comment by Mike-E-angelo** [comment]
Hmmm... this is what I see when attempting to publish:

![](https://i.imgur.com/PQiO4HM.png)

Settings:

![](https://i.imgur.com/Hvtq7HG.png)

It seems that message is being used for format?

**Comment by donaldwasserman** [comment]
So we need to make the label more clear here. On our side `Tag Format` is Github's tag name. I'll reopen this and close it when i update the label
