### ISSUE TITLE
Summary is Ignored

### ISSUE THREAD

**Issue by Mike-E-angelo** [nextreleaseio/next-release#22]
Got one more here for you. 😇

It would seem that the `Summary` field:

![](https://i.imgur.com/SV3oYNY.png)

Does not make it into the release's final copy:

https://github.com/ExtendedXmlSerializer/NextRelease/releases/tag/1.0.0

**Comment by donaldwasserman** [comment]
@Mike-EEE THis should be fixed now.

**Comment by Mike-E-angelo** [comment]
Woohoo!  This was really the only one that was considered blocking.  Now I can launch a release. :D
