### ISSUE TITLE
Release Draft is Not Created on GitHub

### ISSUE THREAD

**Issue by Mike-E-angelo** [nextreleaseio/next-release#23]
I spoke with Donald on Intercom about this and want to make sure it's captured somewhere so that I am not hassling him about it with a support chat. 😅

It was mentioned that Next Release creates a draft release on GitHub from your current Next Release data.  Currently, there is something that is keeping this from working as advertised and Donald is looking into it.

This would, of course, be super valuable if we have a release member/manager who for some reason doesn't have experience with Next Release and is asked to create a release from what's on GitHub.

**Comment by Mike-E-angelo** [comment]
This, too, still appears to be an issue... 😞

**Comment by donaldwasserman** [comment]
How are you publishing the release?

**Comment by Mike-E-angelo** [comment]
Currently via GitHub due to the current publishing issues (btw you can see from [this image](https://i.imgur.com/YyV6aoK.png) we're still set to `3.2.0` and not `3.1.1` as expected -- not sure if it's been reset yet or not, however).

I guess the understanding was that a preview release was made in GitHub alongside the NextRelease version which this issue was meant to track, but that doesn't appear to be the case.

**Comment by Mike-E-angelo** [comment]
And here I thought you were just giving me the cold shoulder 😆:

![](https://i.imgur.com/pfM7omw.png)

VERY COOL!!!

**Comment by donaldwasserman** [comment]
👍
