### ISSUE TITLE
Incorrect Line Breaks

### ISSUE THREAD

**Issue by Mike-E-angelo** [nextreleaseio/next-release#24]
Alrighty!  Did our first release... the summary got in there (yay!), but the generated issues suffer from linebreak problems (boo):

https://i.imgur.com/9l76oJc.gifv

**Comment by Mike-E-angelo** [comment]
Fixed them here, FWIW:

https://github.com/ExtendedXmlSerializer/home/releases/tag/3.0.0

**Comment by donaldwasserman** [comment]
Sorry about that - I messed that up. Should be good now though.

**Comment by Mike-E-angelo** [comment]
Dang! FAST!  Thanks you much!

**Comment by donaldwasserman** [comment]
It won't update until you update the release with a new pull request or on editing one of the fields.
