### ISSUE TITLE
Release Commit Does Not Appear to Refresh

### ISSUE THREAD

**Issue by Mike-E-angelo** [nextreleaseio/next-release#25]
Found another one. 😁

We attempted to push another release just now.  However, it seems the release selected the wrong commit, unfortunately.  My hunch is that the commit is stored somehow when the `Edit Release` screen is called (or `Pending Release` is loaded), and that is the commit used to when creating a release.

Ideally, the `Create Release` should do a refresh at execution time to update the latest commit on `master` (or configured) branch.  Or even better, allow the user to select the commit so there is no ambiguity. 👍

**Comment by donaldwasserman** [comment]
@Mike-EEE Sent you an email to get some more details on this.
